/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteRouteImport } from './routes/app/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AppIndexRouteImport } from './routes/app/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as AppBillingRouteImport } from './routes/app/billing'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as AppApplicationsIndexRouteImport } from './routes/app/applications/index'
import { Route as AppApplicationsCreateRouteImport } from './routes/app/applications/create'
import { Route as AppApplicationsApplicationIdRouteImport } from './routes/app/applications/$applicationId'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'

const AppRouteRoute = AppRouteRouteImport.update({
  id: '/app',
  path: '/app',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRouteRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const AppBillingRoute = AppBillingRouteImport.update({
  id: '/billing',
  path: '/billing',
  getParentRoute: () => AppRouteRoute,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AppApplicationsIndexRoute = AppApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApplicationsCreateRoute = AppApplicationsCreateRouteImport.update({
  id: '/applications/create',
  path: '/applications/create',
  getParentRoute: () => AppRouteRoute,
} as any)
const AppApplicationsApplicationIdRoute =
  AppApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AppRouteRoute,
  } as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/generate': typeof ApiGenerateRoute
  '/app/billing': typeof AppBillingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/app/applications/create': typeof AppApplicationsCreateRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/app/billing': typeof AppBillingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/app': typeof AppIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/app/applications/create': typeof AppApplicationsCreateRoute
  '/app/applications': typeof AppApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/app': typeof AppRouteRouteWithChildren
  '/api/generate': typeof ApiGenerateRoute
  '/app/billing': typeof AppBillingRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/app/': typeof AppIndexRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/app/applications/$applicationId': typeof AppApplicationsApplicationIdRoute
  '/app/applications/create': typeof AppApplicationsCreateRoute
  '/app/applications/': typeof AppApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/app'
    | '/api/generate'
    | '/app/billing'
    | '/sign-in/$'
    | '/app/'
    | '/api/webhooks/clerk'
    | '/app/applications/$applicationId'
    | '/app/applications/create'
    | '/app/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generate'
    | '/app/billing'
    | '/sign-in/$'
    | '/app'
    | '/api/webhooks/clerk'
    | '/app/applications/$applicationId'
    | '/app/applications/create'
    | '/app/applications'
  id:
    | '__root__'
    | '/'
    | '/app'
    | '/api/generate'
    | '/app/billing'
    | '/sign-in/$'
    | '/app/'
    | '/api/webhooks/clerk'
    | '/app/applications/$applicationId'
    | '/app/applications/create'
    | '/app/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AppRouteRoute: typeof AppRouteRouteWithChildren
  ApiGenerateRoute: typeof ApiGenerateRoute
  SignInSplatRoute: typeof SignInSplatRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/app': {
      id: '/app'
      path: '/app'
      fullPath: '/app'
      preLoaderRoute: typeof AppRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/': {
      id: '/app/'
      path: '/'
      fullPath: '/app/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/billing': {
      id: '/app/billing'
      path: '/billing'
      fullPath: '/app/billing'
      preLoaderRoute: typeof AppBillingRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/app/applications/': {
      id: '/app/applications/'
      path: '/applications'
      fullPath: '/app/applications/'
      preLoaderRoute: typeof AppApplicationsIndexRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/applications/create': {
      id: '/app/applications/create'
      path: '/applications/create'
      fullPath: '/app/applications/create'
      preLoaderRoute: typeof AppApplicationsCreateRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/app/applications/$applicationId': {
      id: '/app/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/app/applications/$applicationId'
      preLoaderRoute: typeof AppApplicationsApplicationIdRouteImport
      parentRoute: typeof AppRouteRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AppRouteRouteChildren {
  AppBillingRoute: typeof AppBillingRoute
  AppIndexRoute: typeof AppIndexRoute
  AppApplicationsApplicationIdRoute: typeof AppApplicationsApplicationIdRoute
  AppApplicationsCreateRoute: typeof AppApplicationsCreateRoute
  AppApplicationsIndexRoute: typeof AppApplicationsIndexRoute
}

const AppRouteRouteChildren: AppRouteRouteChildren = {
  AppBillingRoute: AppBillingRoute,
  AppIndexRoute: AppIndexRoute,
  AppApplicationsApplicationIdRoute: AppApplicationsApplicationIdRoute,
  AppApplicationsCreateRoute: AppApplicationsCreateRoute,
  AppApplicationsIndexRoute: AppApplicationsIndexRoute,
}

const AppRouteRouteWithChildren = AppRouteRoute._addFileChildren(
  AppRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AppRouteRoute: AppRouteRouteWithChildren,
  ApiGenerateRoute: ApiGenerateRoute,
  SignInSplatRoute: SignInSplatRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
