/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as AuthedIndexRouteImport } from './routes/_authed/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as AuthedApplicationsNewRouteImport } from './routes/_authed/applications/new'
import { Route as AuthedApplicationsApplicationIdRouteImport } from './routes/_authed/applications/$applicationId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedIndexRoute = AuthedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthedRoute,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedApplicationsNewRoute = AuthedApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplicationsApplicationIdRoute =
  AuthedApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthedIndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/applications/new': typeof AuthedApplicationsNewRoute
}
export interface FileRoutesByTo {
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/': typeof AuthedIndexRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/applications/new': typeof AuthedApplicationsNewRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authed': typeof AuthedRouteWithChildren
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRoute
  '/sign-in/$': typeof SignInSplatRoute
  '/_authed/': typeof AuthedIndexRoute
  '/_authed/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/_authed/applications/new': typeof AuthedApplicationsNewRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/generate'
    | '/api/health'
    | '/sign-in/$'
    | '/applications/$applicationId'
    | '/applications/new'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/api/generate'
    | '/api/health'
    | '/sign-in/$'
    | '/'
    | '/applications/$applicationId'
    | '/applications/new'
  id:
    | '__root__'
    | '/_authed'
    | '/api/generate'
    | '/api/health'
    | '/sign-in/$'
    | '/_authed/'
    | '/_authed/applications/$applicationId'
    | '/_authed/applications/new'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHealthRoute: typeof ApiHealthRoute
  SignInSplatRoute: typeof SignInSplatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/': {
      id: '/_authed/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthedIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/applications/new': {
      id: '/_authed/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof AuthedApplicationsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/applications/$applicationId': {
      id: '/_authed/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedIndexRoute: typeof AuthedIndexRoute
  AuthedApplicationsApplicationIdRoute: typeof AuthedApplicationsApplicationIdRoute
  AuthedApplicationsNewRoute: typeof AuthedApplicationsNewRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedIndexRoute: AuthedIndexRoute,
  AuthedApplicationsApplicationIdRoute: AuthedApplicationsApplicationIdRoute,
  AuthedApplicationsNewRoute: AuthedApplicationsNewRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AuthedRoute: AuthedRouteWithChildren,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHealthRoute: ApiHealthRoute,
  SignInSplatRoute: SignInSplatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
