/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AuthedRouteImport } from './routes/_authed'
import { Route as IndexRouteImport } from './routes/index'
import { Route as SignInSplatRouteImport } from './routes/sign-in.$'
import { Route as ApiHealthRouteImport } from './routes/api/health'
import { Route as ApiGenerateRouteImport } from './routes/api/generate'
import { Route as AuthedApplicationsIndexRouteImport } from './routes/_authed/applications/index'
import { Route as ApiWebhooksClerkRouteImport } from './routes/api/webhooks/clerk'
import { Route as ApiHealthReadyRouteImport } from './routes/api/health.ready'
import { Route as ApiCronJobRouteImport } from './routes/api/cron.$job'
import { Route as AuthedApplicationsNewRouteImport } from './routes/_authed/applications/new'
import { Route as AuthedApplicationsBillingRouteImport } from './routes/_authed/applications/billing'
import { Route as AuthedApplicationsApplicationIdRouteImport } from './routes/_authed/applications/$applicationId'

const AuthedRoute = AuthedRouteImport.update({
  id: '/_authed',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const SignInSplatRoute = SignInSplatRouteImport.update({
  id: '/sign-in/$',
  path: '/sign-in/$',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthRoute = ApiHealthRouteImport.update({
  id: '/api/health',
  path: '/api/health',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiGenerateRoute = ApiGenerateRouteImport.update({
  id: '/api/generate',
  path: '/api/generate',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedApplicationsIndexRoute = AuthedApplicationsIndexRouteImport.update({
  id: '/applications/',
  path: '/applications/',
  getParentRoute: () => AuthedRoute,
} as any)
const ApiWebhooksClerkRoute = ApiWebhooksClerkRouteImport.update({
  id: '/api/webhooks/clerk',
  path: '/api/webhooks/clerk',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiHealthReadyRoute = ApiHealthReadyRouteImport.update({
  id: '/ready',
  path: '/ready',
  getParentRoute: () => ApiHealthRoute,
} as any)
const ApiCronJobRoute = ApiCronJobRouteImport.update({
  id: '/api/cron/$job',
  path: '/api/cron/$job',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthedApplicationsNewRoute = AuthedApplicationsNewRouteImport.update({
  id: '/applications/new',
  path: '/applications/new',
  getParentRoute: () => AuthedRoute,
} as any)
const AuthedApplicationsBillingRoute =
  AuthedApplicationsBillingRouteImport.update({
    id: '/applications/billing',
    path: '/applications/billing',
    getParentRoute: () => AuthedRoute,
  } as any)
const AuthedApplicationsApplicationIdRoute =
  AuthedApplicationsApplicationIdRouteImport.update({
    id: '/applications/$applicationId',
    path: '/applications/$applicationId',
    getParentRoute: () => AuthedRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/applications/billing': typeof AuthedApplicationsBillingRoute
  '/applications/new': typeof AuthedApplicationsNewRoute
  '/api/cron/$job': typeof ApiCronJobRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/applications/': typeof AuthedApplicationsIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/applications/billing': typeof AuthedApplicationsBillingRoute
  '/applications/new': typeof AuthedApplicationsNewRoute
  '/api/cron/$job': typeof ApiCronJobRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/applications': typeof AuthedApplicationsIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authed': typeof AuthedRouteWithChildren
  '/api/generate': typeof ApiGenerateRoute
  '/api/health': typeof ApiHealthRouteWithChildren
  '/sign-in/$': typeof SignInSplatRoute
  '/_authed/applications/$applicationId': typeof AuthedApplicationsApplicationIdRoute
  '/_authed/applications/billing': typeof AuthedApplicationsBillingRoute
  '/_authed/applications/new': typeof AuthedApplicationsNewRoute
  '/api/cron/$job': typeof ApiCronJobRoute
  '/api/health/ready': typeof ApiHealthReadyRoute
  '/api/webhooks/clerk': typeof ApiWebhooksClerkRoute
  '/_authed/applications/': typeof AuthedApplicationsIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/api/generate'
    | '/api/health'
    | '/sign-in/$'
    | '/applications/$applicationId'
    | '/applications/billing'
    | '/applications/new'
    | '/api/cron/$job'
    | '/api/health/ready'
    | '/api/webhooks/clerk'
    | '/applications/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/api/generate'
    | '/api/health'
    | '/sign-in/$'
    | '/applications/$applicationId'
    | '/applications/billing'
    | '/applications/new'
    | '/api/cron/$job'
    | '/api/health/ready'
    | '/api/webhooks/clerk'
    | '/applications'
  id:
    | '__root__'
    | '/'
    | '/_authed'
    | '/api/generate'
    | '/api/health'
    | '/sign-in/$'
    | '/_authed/applications/$applicationId'
    | '/_authed/applications/billing'
    | '/_authed/applications/new'
    | '/api/cron/$job'
    | '/api/health/ready'
    | '/api/webhooks/clerk'
    | '/_authed/applications/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthedRoute: typeof AuthedRouteWithChildren
  ApiGenerateRoute: typeof ApiGenerateRoute
  ApiHealthRoute: typeof ApiHealthRouteWithChildren
  SignInSplatRoute: typeof SignInSplatRoute
  ApiCronJobRoute: typeof ApiCronJobRoute
  ApiWebhooksClerkRoute: typeof ApiWebhooksClerkRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_authed': {
      id: '/_authed'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sign-in/$': {
      id: '/sign-in/$'
      path: '/sign-in/$'
      fullPath: '/sign-in/$'
      preLoaderRoute: typeof SignInSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health': {
      id: '/api/health'
      path: '/api/health'
      fullPath: '/api/health'
      preLoaderRoute: typeof ApiHealthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/generate': {
      id: '/api/generate'
      path: '/api/generate'
      fullPath: '/api/generate'
      preLoaderRoute: typeof ApiGenerateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/applications/': {
      id: '/_authed/applications/'
      path: '/applications'
      fullPath: '/applications/'
      preLoaderRoute: typeof AuthedApplicationsIndexRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/api/webhooks/clerk': {
      id: '/api/webhooks/clerk'
      path: '/api/webhooks/clerk'
      fullPath: '/api/webhooks/clerk'
      preLoaderRoute: typeof ApiWebhooksClerkRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/health/ready': {
      id: '/api/health/ready'
      path: '/ready'
      fullPath: '/api/health/ready'
      preLoaderRoute: typeof ApiHealthReadyRouteImport
      parentRoute: typeof ApiHealthRoute
    }
    '/api/cron/$job': {
      id: '/api/cron/$job'
      path: '/api/cron/$job'
      fullPath: '/api/cron/$job'
      preLoaderRoute: typeof ApiCronJobRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authed/applications/new': {
      id: '/_authed/applications/new'
      path: '/applications/new'
      fullPath: '/applications/new'
      preLoaderRoute: typeof AuthedApplicationsNewRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/applications/billing': {
      id: '/_authed/applications/billing'
      path: '/applications/billing'
      fullPath: '/applications/billing'
      preLoaderRoute: typeof AuthedApplicationsBillingRouteImport
      parentRoute: typeof AuthedRoute
    }
    '/_authed/applications/$applicationId': {
      id: '/_authed/applications/$applicationId'
      path: '/applications/$applicationId'
      fullPath: '/applications/$applicationId'
      preLoaderRoute: typeof AuthedApplicationsApplicationIdRouteImport
      parentRoute: typeof AuthedRoute
    }
  }
}

interface AuthedRouteChildren {
  AuthedApplicationsApplicationIdRoute: typeof AuthedApplicationsApplicationIdRoute
  AuthedApplicationsBillingRoute: typeof AuthedApplicationsBillingRoute
  AuthedApplicationsNewRoute: typeof AuthedApplicationsNewRoute
  AuthedApplicationsIndexRoute: typeof AuthedApplicationsIndexRoute
}

const AuthedRouteChildren: AuthedRouteChildren = {
  AuthedApplicationsApplicationIdRoute: AuthedApplicationsApplicationIdRoute,
  AuthedApplicationsBillingRoute: AuthedApplicationsBillingRoute,
  AuthedApplicationsNewRoute: AuthedApplicationsNewRoute,
  AuthedApplicationsIndexRoute: AuthedApplicationsIndexRoute,
}

const AuthedRouteWithChildren =
  AuthedRoute._addFileChildren(AuthedRouteChildren)

interface ApiHealthRouteChildren {
  ApiHealthReadyRoute: typeof ApiHealthReadyRoute
}

const ApiHealthRouteChildren: ApiHealthRouteChildren = {
  ApiHealthReadyRoute: ApiHealthReadyRoute,
}

const ApiHealthRouteWithChildren = ApiHealthRoute._addFileChildren(
  ApiHealthRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthedRoute: AuthedRouteWithChildren,
  ApiGenerateRoute: ApiGenerateRoute,
  ApiHealthRoute: ApiHealthRouteWithChildren,
  SignInSplatRoute: SignInSplatRoute,
  ApiCronJobRoute: ApiCronJobRoute,
  ApiWebhooksClerkRoute: ApiWebhooksClerkRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
